- hosts: all
  become: true
  roles:
   - common
   - docker
  tasks:
    - include_role:
        name: swarm-init
      when: ismaster == 'true'
    - include_role:
        name: swarm-join
      when: "ismaster != 'true'"